#!/bin/sh
/usr/bin/aegis-exec -s -u user /usr/bin/gconftool -s --type=int /apps/Callmee/Active 1
/usr/bin/aegis-exec -s -u user /usr/bin/gconftool -s --type=int /apps/Callmee/Delay 2

/sbin/initctl start apps/callmee

exit 0
